### ISSUE TITLE
Google Analytics tracking

### ISSUE THREAD

**Issue by stedmanblake** [stedmanblake/chativism#48]
- [] Add basic tracking to the site;
- [] List all events we'd want to track
- [] Consider Heap (free for <5000 sessions / month)

**Comment by barneyjackson** [comment]
I think we should embellish our tracking to be as precise as possible, however best that is done (Heap? Mixpanel?). Having insight into exactly which reps are being called and on which issues feels pretty vital to progressing the product.
