### ISSUE TITLE
Meta Data

### ISSUE THREAD

**Issue by barneyjackson** [stedmanblake/chativism#62]
FB og: fields & probably twitter.

This means we need a good image, an great tag line, and an even better 250 char blurb.

**Comment by barneyjackson** [comment]
- [ ] Twitter not 'whitelisted'? (https://cards-dev.twitter.com/validator)
- [ ] FB seems to scrape just the skeletal `index.html`, doesn't look in `bundle.js`, so doesn't get the meta fields from Helmet. This should work.
- [ ] `DOMAIN` env var doesn't seem to be pulling at all
